### Update an existing patient entity
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "mike mentzer",
  "email": "test3@gmail.com",
  "address": "new jersey",
  "dateOfBirth": "2001-07-06"
}

###